code --install-extension amazonwebservices.aws-toolkit-vscode --force
code --install-extension atlassian.atlascode --force
code --install-extension aws-scripting-guy.cform --force
code --install-extension chef-software.chef --force
code --install-extension CoenraadS.bracket-pair-colorizer --force
code --install-extension dave-hagedorn.jenkins-runner --force
code --install-extension DavidAnson.vscode-markdownlint --force
code --install-extension donjayamanne.githistory --force
code --install-extension eamodio.gitlens --force
code --install-extension formulahendry.docker-explorer --force
code --install-extension formulahendry.vscode-mysql --force
code --install-extension GitHub.remotehub --force
code --install-extension GitHub.vscode-pull-request-github --force
code --install-extension googlecloudtools.cloudcode --force
code --install-extension hashicorp.terraform --force
code --install-extension hediet.vscode-drawio --force
code --install-extension henriiik.docker-linter --force
code --install-extension HookyQR.beautify --force
code --install-extension humao.rest-client --force
code --install-extension janjoerke.jenkins-pipeline-linter-connector --force
code --install-extension marlon407.code-groovy --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension ms-toolsai.jupyter-keymap --force
code --install-extension ms-toolsai.jupyter-renderers --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vscode-remote.remote-ssh --force
code --install-extension ms-vscode.powershell --force
code --install-extension oderwat.indent-rainbow --force
code --install-extension p1c2u.docker-compose --force
code --install-extension pflannery.vscode-versionlens --force
code --install-extension rebornix.ruby --force
code --install-extension redhat.vscode-commons --force
code --install-extension redhat.vscode-xml --force
code --install-extension redhat.vscode-yaml --force
code --install-extension secanis.jenkinsfile-support --force
code --install-extension Shan.code-settings-sync --force
code --install-extension shardulm94.trailing-spaces --force
code --install-extension SonarSource.sonarlint-vscode --force
code --install-extension TabNine.tabnine-vscode --force
code --install-extension timonwong.shellcheck --force
code --install-extension tomoki1207.pdf --force
code --install-extension VisualStudioExptTeam.vscodeintellicode --force
code --install-extension vscode-aws-console.vscode-aws-console --force
code --install-extension vscode-icons-team.vscode-icons --force
code --install-extension vscodevim.vim --force
code --install-extension wingrunr21.vscode-ruby --force
code --install-extension yzhang.markdown-all-in-one --force